FROM condaforge/mambaforge:23.3.1-0

# Create preparation environment
COPY envs/environment_prepare.yaml .
RUN mamba env create -f environment_prepare.yaml \
    && mamba clean -afy

# Initialize conda
RUN conda init bash

# Set working directory
WORKDIR /repository

# Set the default command to run preparation directly
ENTRYPOINT ["/opt/conda/envs/agentomics-prepare-env/bin/python", "/repository/src/prepare_datasets.py"]
CMD ["--prepare-all"]