name: fm-download-env
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - pip:
    - PyYAML==6.0.2
    - torch==2.9.0
    - transformers==4.47.1
    - einops==0.8.1
    - multimolecule==0.0.8
