name: aideml-env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - scikit-learn
  - cxx-compiler
  - libxcrypt
  - openai
  - pip:
    - hrid
    - wandb
    - aideml
    - python-dotenv

