name: oneshot-env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - openai
  - pip
  - scikit-learn
  - pip:
    - wandb
    - hrid
    - python-dotenv
    - timeout-function-decorator