#!/bin/bash

# Check if work_dir path is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <work_dir_path>"
    echo "Please provide a work dir path as an argument (e.g., /workspace/runs/agent_id)"
    exit 1
fi

WORK_DIR_ARG=$1
TARGET_YAML_PATH="/tmp/MetaGPT_fork_sela/metagpt/ext/sela/data.yaml"
DATASETS_DIR="/repository/Agentomics-ML/datasets" # Use correct dataset path
ROLE_DIR="storage/SELA" # Relative path within work_dir

echo "Writing data.yaml to: $TARGET_YAML_PATH"
echo " Using work_dir: $WORK_DIR_ARG"
echo " Using datasets_dir: $DATASETS_DIR"

# Ensure target directory exists (though it should from git clone)
mkdir -p "$(dirname "$TARGET_YAML_PATH")"

# Create data.yaml file using the absolute path
cat > "$TARGET_YAML_PATH" << EOF
# This file is automatically generated by overwrite_data_yaml.sh
datasets_dir: "$DATASETS_DIR" # path to the datasets directory (corrected)
work_dir: "$WORK_DIR_ARG" # path to the specific run's workspace directory
role_dir: "$ROLE_DIR" # relative path to the role directory within work_dir
EOF

echo "Augmented data.yaml successfully written."

